config/routes.rb
Rails.application.routes.draw do
 
    get 'about', to: 'posts#about', as: :about 
     get 'browse', to: 'posts#browse', as: :browse_posts 
   post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
    
get 'notifications', to: 'notifications#index' 

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }  
    resources :posts do  
        resources :comments
    end  
    
    get ':user_name', to: 'profiles#show', as: :profile  
    get ':user_name/edit', to: 'profiles#edit', as: :edit_profile  
    patch ':user_name/edit', to: 'profiles#update', as: :update_profile  
    
    resources :posts do  
        resources :comments
        member do
            get 'like'
        end
    end 
    

    root 'posts#index'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    
      before_action :set_user
      before_action :owned_profile, only: [:edit, :update]
      before_action :authenticate_user!  

    
    def edit  
        @user = User.find_by(user_name: params[:user_name])
    end
    
    def show
        @user = User.find_by(user_name: params[:user_name])
        @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
    end
    
    def update  
        @user = User.find_by(user_name: params[:user_name])
        if @user.update(profile_params)
            flash[:success] = 'Your profile has been updated.'
            redirect_to profile_path(@user.user_name)
        else
            @user.errors.full_messages
            flash[:error] = @user.errors.full_messages
            render :edit
        end
    end 
    
    private
    def profile_params  
        params.require(:user).permit(:avatar, :bio)
    end 
    
    private
    def owned_profile  
        @user = User.find_by(user_name: params[:user_name])
        unless current_user == @user
            flash[:alert] = "That profile doesn't belong to you!"
            redirect_to root_path
        end
    end
    
    private
    def set_user  
        @user = User.find_by(user_name: params[:user_name])
    end
    
end

app/helpers/profiles_helper.rb
module ProfilesHelper  
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end 

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Change your profile image:</h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/follow_user.js.erb
/*$('#follow-button').attr('class', 'btn unfollow-button')
                   .text('Following')
                   .attr('href', "/<%= @user.user_name %>/unfollow_user")
                   .attr('id', 'unfollow-button');*/

$(document).on('click', '.btn.unfollow-button', function(){
   alert("I am here");
    $('#follow-button').attr('class', 'btn unfollow-button').text('Following').attr('href', "/<%= @user.user_name %>/unfollow_user").attr('id', 'unfollow-button');
     
});

app/views/profiles/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
   <div class="col-md-6 col-sm-6">
            <% if @user.avatar_file_name.to_s.include?("googleusercontent") %>
        <% imagesource = @user.avatar_file_name %>
       <% elsif @user.avatar_file_name.to_s.length == 0%>
          <%  imagesource = 'assets/default-avatar.jpg' %>
          
      <% else %>
          <%  imagesource = @user.avatar.url %>
        
      <% end %>
      <img class="img-circle" src="<%= imagesource%>" width="180" height="180" >
    
    </div>
    
    <div class="col-md-6 col-sm-6" style="margin-top:.4cm; text-align:center;">
      <div class="user-name-and-follow">
    <div class="col-md-6 col-sm-6" >
        <h3 class="profile-user-name pull-left">
            <% if @user.user_name.length > 15 %>
                    <%= @user.name %><br>   
            <% else %>
                 <%= @user.user_name %><br>   
            <% end %>
        </h3>
     </div>
       <div class="col-md-6 col-sm-6" > 
        <span >
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_profile_path(@user.user_name), :class => 'btn edit-button' %>
        
         <% elsif current_user_is_following(current_user.id, @user.id) %>
            <%= link_to 'Following', unfollow_user_path,  :remote => true,:class => 'btn unfollow-button',:id => 'unfollow-button',:method => :post%>
          <% else %>
            <%= link_to 'Follow', follow_user_path, remote: true,class: 'btn follow-button', id: 'follow-button', :method => :post %>
          <% end %>
       </span> 
           </div> 
    </div>
      <div class="col-md-12 col-sm-12" >      
          <h6 class="userEmail"><%= @user.email %></h6> 
       </div>
       <div class="col-md-12 col-sm-12" >     
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      <div class="user-statistics">
        <p>
          <%= pluralize @user.posts.count, 'post' %>
        </p>
      </div>
    </div>
    </div>
      <script>
      $(document).on('click', '#follow-button', function(){
       alert("You started following this User.");
        $('#follow-button').attr('class', 'btn unfollow-button')
                           .text('Following')
                           .attr('href', "/<%= @user.user_name %>/unfollow_user").attr('id', 'unfollow-button');          
     });
          
      $(document).on('click', '#unfollow-button', function(){
       alert("You have unfollowed this User");
       $('#unfollow-button').text('Follow')
                         .attr('class', 'btn follow-button')
                         .attr('href', "/<%= @user.user_name %>/follow_user")
                         .attr('id', 'follow-button');
     });


      </script>
  </div>
</div>


<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/profiles/unfollow_user.js.erb
$('#unfollow-button').text('Follow')
                     .attr('class', 'btn follow-button')
                     .attr('href', "/<%= @user.user_name %>/follow_user")
                     .attr('id', 'follow-button');