config/routes.rb
Rails.application.routes.draw do
 
    get 'about', to: 'posts#about', as: :about 
     get 'browse', to: 'posts#browse', as: :browse_posts 
   post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
    
get 'notifications', to: 'notifications#index' 

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }  
    resources :posts do  
        resources :comments
    end  
    
    get ':user_name', to: 'profiles#show', as: :profile  
    get ':user_name/edit', to: 'profiles#edit', as: :edit_profile  
    patch ':user_name/edit', to: 'profiles#update', as: :update_profile  
    
    resources :posts do  
        resources :comments
        member do
            get 'like'
        end
    end 
    

    root 'posts#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notified_by, class_name: 'User'
  belongs_to :user
  belongs_to :subscribed_user
  belongs_to :post
    
   validates :user_id, :notified_by_id, :post_id, :identifier, :notice_type, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def link_through
       @notification = Notification.find(params[:id])
  @notification.update read: true
  redirect_to post_path @notification.post
  end
    
    
    def index  
        @notifications = current_user.notifications
    end 
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% if notification.notified_by.avatar_file_name.to_s.include?("googleusercontent") %>
        <% imagesource = notification.notified_by.avatar_file_name %>
       <% elsif notification.notified_by.avatar_file_name.to_s.length == 0%>
          <%  imagesource = 'assets/default-avatar.jpg' %>
          
      <% else %>
          <%  imagesource = notification.notified_by.avatar.url %>
        
      <% end %>



<li>
    <img class="img-circle" style="border-radius:100%; width:1cm; height:1cm " src=" <%= imagesource %>
      ">
       
      
  

    
  <%= link_to "#{notification.notified_by.user_name} has #{notification.notice_type}ed on your post", link_through_path(notification) %>
<%= time_ago_in_words notification.created_at %> ago

</li>

app/views/notifications/_notification_dropdown.html.erb
<li>
    <div class="dropdown notification-dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
           <%= current_user.notifications.where(read: false).count %>
            <span class="glyphicon glyphicon-flag"></span> </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" style="background-color: darkblue">
            <li class="dropdown-header text-center" style="color:white">Notifications</li>
            <%= render current_user.notifications.where(read: false).order('created_at DESC').last(5) %>
            <li class="divider" role="separator">
  <li class="text-center">
    <%= link_to 'View All', notifications_path %>
  </li>
</li>

        </ul>
    </div>
</li>

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-6 col-md-offset-3">
         
          <ul class="notification-unread-list">
               <h2> Unread Notifications</h2>
          <%= render current_user.notifications.where(read: false).order('created_at DESC') %>
          </ul>
      </div>
      
      <div class="col-md-6 col-md-offset-3">
          
          <ul class="notification-read-list">
              <h2> Read Notifications</h2>
          <%= render current_user.notifications.where(read: true).order('created_at DESC') %>
          </ul>
      </div>
  </div>
</div>

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>