config/routes.rb
Rails.application.routes.draw do
 
    get 'about', to: 'posts#about', as: :about 
     get 'browse', to: 'posts#browse', as: :browse_posts 
   post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
    
get 'notifications', to: 'notifications#index' 

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }  
    resources :posts do  
        resources :comments
    end  
    
    get ':user_name', to: 'profiles#show', as: :profile  
    get ':user_name/edit', to: 'profiles#edit', as: :edit_profile  
    patch ':user_name/edit', to: 'profiles#update', as: :update_profile  
    
    resources :posts do  
        resources :comments
        member do
            get 'like'
        end
    end 
    

    root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
    acts_as_votable
    
    validates :user_id, presence: true 
    validates :image, presence: true

  has_attached_file :image, styles: { :medium => "550x400!" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
    
    belongs_to :user 
    has_many :comments, dependent: :destroy
    
    has_many :notifications, dependent: :destroy  
    
    scope :of_followed_users, -> (following_users) { where user_id: following_users }  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :set_post, only: [:show, :edit, :update, :destroy, :like] 
    before_action :authenticate_user!  
    before_action :owned_post, only: [:edit, :update, :destroy]  
    
    def about
      
    end
    
    def index
       @posts = Post.of_followed_users(current_user.following).order('created_at DESC').page params[:page]
    end
    
    def browse  
        @posts = Post.all.order('created_at DESC').page params[:page]
    end 
    
    def show
    end
    
    def edit  
    end

    def update  
        if @post.update(post_params)
            flash[:success] = "Post updated."
           redirect_to posts_path
        else
            flash.now[:alert] = "Update failed.  Please check the form."
           render :edit
        end
    end
    
    def destroy  
       @post.destroy
       redirect_to posts_path
    end
    
    def like
        if @post.liked_by current_user
            respond_to do |format|
                format.html { redirect_to :back }
                format.js
            end
        end
    end
    
    
    def new
        @post = current_user.posts.build
    end
    
    def create
         @post = current_user.posts.build(post_params)

         if @post.save
             flash[:success] = "Your post has been created!"
             redirect_to posts_path
         else
            flash[:alert] = "Your new post couldn't be created!  Please check the form."
            render :new
         end
    end
    
    private
    def post_params
        params.require(:post).permit(:image, :caption)
    end 
    
    private
    def set_post
       @post = Post.find(params[:id])
    end
    
    private
    def owned_post  
        unless current_user == @post.user
            flash[:alert] = "That post doesn't belong to you!"
            redirect_to root_path
        end
    end  
    
   
        
end

app/helpers/posts_helper.rb
module PostsHelper  
  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 8
    count_likers(votes)
  end

  def liked_post(post)
    return 'glyphicon-heart' if current_user.voted_for? post
    'glyphicon-heart-empty'
  end

  private

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.name,
            profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end
end  

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_image_select(@post) %>
        <%= simple_form_for @post, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4>Upload an image:</h4>
              <%= f.input :image, label: false, input_html: { onChange: 'loadFile(event)' } %>
            </div>
            <div class="form-group text-center">
              <%= f.input :caption, label: false, placeholder: 'Add your caption' %>
            </div>
            <div class="form-group text-center">
              <%= f.button :submit, class: 'btn-success btn-block' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_likes.html.erb
<div class="likes" id="likes_<%= post.id %>">
  <%= display_likes post %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
    
    <div class="post">
        
        <div class="post-head">
            <div class="thumb-img"></div>
            <% if post.user.avatar_file_name.to_s.include?("googleusercontent") %>
               <% imagesource = post.user.avatar_file_name %>
            <% elsif post.user.avatar_file_name.to_s.length == 0%>
               <%  imagesource = 'assets/default-avatar.jpg' %>
            <% else %>
               <%  imagesource = post.user.avatar.url %>
            <% end %>
            
            <div class="user-name">
                <img class="img-circle" style="border-radius:100%; width:1cm; height:1cm " src="<%= imagesource %>">
                <%= link_to post.user.name, profile_path(post.user.user_name) %>
            </div>
        </div>
        
        <div class="image center-block">
            <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
        </div>
        
        <div class="post-bottom">
            <%= render 'posts/likes', post: post %>
            <div class="caption">
                <div class="caption-content">
                    <div class="user-name">
                        <% if post.user.user_name.length > 15 %>
                        <%= link_to post.user.name, profile_path(post.user.user_name) %>
                        <% else %>
                        <%= link_to post.user.name, profile_path(post.user.user_name) %>
                        <% end %>
                    </div>
                    <div class="time-ago">
                        <%= time_ago_in_words post.created_at %>
                    </div>
                    <%= post.caption %>
                </div>
                <div class="comments" id="comments_<%= post.id %>">
                    <% if post.comments.any? %>
                    <div class="paginator" id="#comments-paginator-<%= post.id %>">
                        <% unless post.comments.count <= 4 %>
                        <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', id: "more_comments_#{post.id}", data: {post_id: "#{post.id}", type: "html", value: "#{post.comments.count}"} %>
                        <% end %>
                    </div>
                    <%= render post.comments.last(4), post: post %>
                    <% end %>
                </div>
            </div>
        </div>
        
        <div class="comment-like-form row">
            <div class="col-sm-1 like-button">
                <%= link_to '', like_post_path(post.id), remote: true, id: "like_#{post.id}",class: "glyphicon #{liked_post post}"%>
            </div>
            <div class="comment-form col-sm-11">
                <%= form_for([post, post.comments.build], remote: true) do |f| %>
                <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}" %>
                <% end %>
            </div>
        </div>
    
    </div>
</div>

app/views/posts/_post_dashboard.html.erb
<div id="posts">
  <%= render 'posts' %>
</div>
<div class="text-center" id="paginator">
  <%= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/about.html.erb
<div class="starter-template">
    
    <h1>What is MySnaps?</h1>
    <div class="well well-lg">        
        <p>
            This is a photo-sharing application which enables you to take pictures and share them using this app. Each photograph will have a “Like” button as well as a space for “Comments”. A user can create his account or he can sign-in with his google account. He will also be able to follow other people and like or comment on their pictures.
        </p>        
    </div>
    
    <hr>
    
    <h1>Team</h1>
        <div class="well well-lg">            
            <table style="width: 350px;margin-left: 360px;">
            <tr>
                <td>RITESH KUMAR</td>
                 <td></td>
                <td> SUEELLEN MEDEIRA</td>
            </tr>
            <tr>
                <td><%= image_tag("/ritesh_kumar.jpg", class: 'team_img img-circle') %></td>
                <td></td>
                <td><%= image_tag("/sueellen_medeira.jpg", class: 'team_img img-circle') %></td>
             </tr>
            </table>            
        </div>
    <hr>

    <h1>Contact us</h1>
    <div class="well well-lg">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3847.1969696060423!2d73.93095011484945!3d15.36581528931884!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bbfb75289b5ef5f%3A0x725d94b34ab864f5!2sPersistent+Systems+Ltd.!5e0!3m2!1sen!2sin!4v1466658541040" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen></iframe>
    </div>
        
</div>
    

app/views/posts/browse.html.erb
<%= render 'post_dashboard', posts: @posts %>

app/views/posts/browse.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { 
        $('#paginator').remove(); }  

app/views/posts/edit.html.erb
<%= render 'form' %>
<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", posts_path %>
</div>

app/views/posts/index.html.erb
<%= render 'post_dashboard', posts: @posts %>

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { 
        $('#paginator').remove(); }  

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
    |
    <%= link_to "Edit Post", edit_post_path(@post) %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
  </div>
<% end %>