config/routes.rb
Rails.application.routes.draw do
 
    get 'about', to: 'posts#about', as: :about 
     get 'browse', to: 'posts#browse', as: :browse_posts 
   post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
    
get 'notifications', to: 'notifications#index' 

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }  
    resources :posts do  
        resources :comments
    end  
    
    get ':user_name', to: 'profiles#show', as: :profile  
    get ':user_name/edit', to: 'profiles#edit', as: :edit_profile  
    patch ':user_name/edit', to: 'profiles#update', as: :update_profile  
    
    resources :posts do  
        resources :comments
        member do
            get 'like'
        end
    end 
    

    root 'posts#index'

end

app/views/layouts/_navbar.html.erb
    
    <nav class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "MySnaps", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1" style="background-color: darkblue; ">
      <ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li>
        <%= render 'notifications/notification_dropdown' %>
    </li>
    <li>
        <%= link_to "Browse Posts", browse_posts_path %>
    </li>
    <li>
      <%= link_to "New Post", new_post_path %>
    </li>
    <li>
        <%= link_to "My Profile", profile_path(current_user.user_name ) %>
    </li>
    <li>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    </li>
     <li>
        <%= link_to "About", about_path%>
    </li>
  <% else %>
    <li>
      <%= link_to "Login", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Register", new_user_registration_path %>
    </li>
  <% end %>
</ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mysnaps</title>
<%= favicon_link_tag 'f.png' %>
<meta name="viewport" content="width=device-width, initial-scale=1">
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    
<%= render 'layouts/navbar' %>

<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>
</head>
<body>
    
<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
  <% end %>
  <%= yield %>
</div>

    


</body>
</html>